services:
- docker

env:
  global:
  - DOCKER_ACCOUNT=schmandr
  - DOCKER_REPO=oereb-db

branches:
  only:
    - master

script:
  - docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -t $DOCKER_ACCOUNT/$DOCKER_REPO:$TRAVIS_BUILD_NUMBER .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push $DOCKER_ACCOUNT/$DOCKER_REPO:latest
  - docker push $DOCKER_ACCOUNT/$DOCKER_REPO:$TRAVIS_BUILD_NUMBER
